wtf:
  colors:
    border:
      focusable: darkslateblue
      focused: orange
      normal: gray
  grid:
    columns: [32, 32, 32, 32, 32]
    rows: [10, 10, 10, 10, 10, 10, 10]
  refreshInterval: 1
  mods:
    archieve:
      args: ["/var/spool/gammu/archieve"]
      cmd: "ls"
      colors:
        rows:
          even: "lightblue"
          odd: "white"
      enabled: true
      position:
        top: 0
        left: 0
        height: 1
        width: 2
      refreshInterval: 2
      sort: "alphabetical"
      tail: true
      title: "Archieve"
      type: "cmdrunner"
    inbox:
      args: ["/var/spool/gammu/inbox"]
      cmd: "ls"
      colors:
        rows:
          even: "lightblue"
          odd: "white"
      enabled: true
      position:
        top: 0
        left: 2
        height: 1
        width: 2
      refreshInterval: 2
      sort: "alphabetical"
      tail: true
      title: "inbox "
      type: "cmdrunner"
    smsutil:
      args: ["status", "smsutil"]
      cmd: "systemctl"
      colors:
        rows:
          even: "lightblue"
          odd: "white"
      enabled: true
      position:
        top: 1
        left: 0
        height: 2
        width: 4
      refreshInterval: 2
      sort: "alphabetical"
      tail: true
      title: "smsutil "
      type: "cmdrunner"

    gammu-check:
      args: ["status", "gammu-check"]
      cmd: "systemctl"
      colors:
        rows:
          even: "lightblue"
          odd: "white"
      enabled: true
      position:
        top: 3
        left: 0
        height: 2
        width: 4
      refreshInterval: 2
      sort: "alphabetical"
      tail: true
      title: "gammu-check "
      type: "cmdrunner"

    gammu-smsd:
      args: ["/var/log/gammu-smsd"]
      cmd: "tail"
      colors:
        rows:
          even: "lightblue"
          odd: "white"
      enabled: true
      position:
        top: 5
        left: 0
        height: 2
        width: 4
      refreshInterval: 2
      sort: "alphabetical"
      tail: true
      title: "gammu-smsd "
      type: "cmdrunner"

    ipinfo:
      colors:
        name: "lightblue"
        value: "white"
      enabled: true
      position:
        top: 0
        left: 4
        height: 1
        width: 1
      refreshInterval: 150
    resourceusage:
      cpuCombined: false
      enabled: true
      position:
        top: 1
        left: 4
        height: 1
        width: 1
      refreshInterval: 1
      showCPU: true
      showMem: true
      showSwp: true
    security:
      enabled: true
      position:
        top: 0
        left: 5
        height: 1
        width: 1
      refreshInterval: 3600
    lsusb:
      args: []
      cmd: "lsusb"
      colors:
        rows:
          even: "lightblue"
          odd: "white"
      enabled: true
      position:
        top: 2
        left: 4
        height: 1
        width: 2
      refreshInterval: 2
      sort: "alphabetical"
      tail: true
      title: "inbox "
      type: "cmdrunner"
    # feedreader:
    #   enabled: true
    #   feeds:
    #   - http://wtfutil.com/blog/index.xml
    #   feedLimit: 10
    #   position:
    #     top: 1
    #     left: 1
    #     width: 2
    #     height: 1
    #   updateInterval: 14400

    # power:
    #   enabled: true
    #   position:
    #     top: 2
    #     left: 2
    #     height: 1
    #     width: 1
    #   refreshInterval: 15
    #   title: "⚡️"
    # textfile:
    #   enabled: true
    #   filePath: "wtf_config.yml"
    #   format: true
    #   position:
    #     top: 0
    #     left: 0
    #     height: 4
    #     width: 1
    #   refreshInterval: 30
    #   wrapText: false
    # whoami:
    #   args: []
    #   cmd: "ls"
    #   enabled: true
    #   position:
    #     top: 3
    #     left: 1
    #     height: 1
    #     width: 2
    #   refreshInterval: 2
    #   type: cmdrunner
